### ISSUE TITLE
Request-URI Too Long with product-import

### ISSUE THREAD

**Issue by bmnwebshop** [Agence-DnD/PIMGento-2-API#10]
When I want to import products from Akeneo to Magento, I get an error.

Error: Request-URI Too Long

### Environment and configuration
1. Magento Commerce 2.2.5 
2. Akeneo CE 2.3.4 (google cloud)
3a. We had installed the Pimgento2 before we installed this newer version with API. 
3b. Installed PimGento2 (API)  
4. My url of the pim is only: 12 charachters with subdomain,

### Steps to reproduce
1. Backend System -> Pimgento -> Import 
2. Click on "Product"
3. Import Start
Result black screen:

product
[09:15:43] Start import
[09:15:43] Import ID : 5bbf14bf21818
[09:15:43] Create temporary table
[09:15:43] completed
[09:15:43] Fill temporary table
[09:15:43] Request-URI Too Long

### Expected result
1. Finishing product import

### Actual result
Recieve an Error: Request-URI Too Long

**Comment by Dnd-Gimix** [comment]
Dear @bmnwebshop ,

Thank you for using PIMGento2 (API).
Could you try to raise or add the following directive in the Apache configuration of the Magento server : 
LimitRequestLine 

Could you also provide us the configuration of your product import in the Magento 2 admin panel ?

Thank you.

**Comment by bmnwebshop** [comment]
Hi Remi,

We changed the setting on the server, but we use a hypernode + Nginx and no apache.
Hopefully you can help me out. For me it’s strange that “Familys” and “Categories” is working fine, so the connection is working.

Thanks in advance!

Some screenshots of the configuration:

[cid:image001.jpg@01D46483.3C2FB580]


[cid:image002.png@01D46483.3C2FB580]
[cid:image003.png@01D46483.3C2FB580]
[cid:image004.png@01D46483.3C2FB580]

Met vriendelijke groet, Kind regards,

Fons Hofstra
Teammanager E-commerce

BMN | Bouwmaterialen
Celsiusbaan 10 | 3439NC Nieuwegein

M +31 6 26760049
E fons.hofstra@bmn.nl | www.bmn.nl

KvK BMN Bouwmaterialen BV | 01013888

Twitter<https://twitter.com/BMN_Nederland> | Facebook<https://www.facebook.com/BMNNederland>

Houd rekening met het milieu. Print niet meer dan nodig is.

Van: Rémi Verrière [mailto:notifications@github.com]
Verzonden: vrijdag 12 oktober 2018 13:16
Aan: Agence-DnD/PIMGento-2-API
CC: Hofstra, Fons; Mention
Onderwerp: Re: [Agence-DnD/PIMGento-2-API] Request-URI Too Long with product-import (#10)


Dear @bmnwebshop<https://github.com/bmnwebshop> ,

Thank you for using PIMGento2 (API).
Could you try to raise or add the following directive in the Apache configuration of the Magento server :
LimitRequestLine

Could you also provide us the configuration of your product import in the Magento 2 admin panel ?

Thank you.

**Comment by Dnd-Gimix** [comment]
Hi @bmnwebshop ,

For Nginx, could you try to increase the "large_client_header_buffers" configuration following one of those examples : 
- https://stackoverflow.com/questions/1067334/how-to-set-the-allowed-url-length-for-a-nginx-request-error-code-414-uri-too
- http://gbanis.com/blog/howto-troubleshoot-nginx-error-uri-too-large

Also, I can't see any of the images that you provided on the last comment, could you please upload them again ?

Thank you.

**Comment by Dnd-Gimix** [comment]
Hi @bmnwebshop,

Have you tried to change the NGINX setting ?

Thanks.
Regards,

**Comment by Dnd-Gimix** [comment]
Hi @bmnwebshop ,

Did you fixed your Request-URI Too Long issue ?

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @bmnwebshop ,

Did you managed to solve your issue ?

Regards,

**Comment by Dnd-Gimix** [comment]
Hi @bmnwebshop ,

As this issue is not directly related to PIMGento 2 API and without answer, I'll close it.
Feel free to open a new one if necessary ;)

Have a good day.

Regards,

**Comment by karthik32cse** [comment]
**Solution 1:**
Increase the large_client_header_buffers in nginx.conf file http block,
large_client_header_buffers 4 16k;

**Solution 2:**
In my case I have around 700 families. In Akeneo API Configuration page I have choosen one family & excluded rest of the families in Filter Products section and try to import the product. It shows an error like Request-URI Too Long.

After debugging I figured it out the above issues is occured due to the excluded of families. Around 700 query parameters are passing when executing product import.

So the solution is while processing product import. If you have lot of families, exclude only less number of families.

_Let me know if you have any questions_

Regards,
Karthik Dhakshinamoorthy

**Comment by bmnwebshop** [comment]
Hi Karthik,

I don’t use this extension anymore. Sorry about that.

Cheers.
Fons

Met vriendelijke groet, Kind regards,

Fons Hofstra
Teammanager E-commerce

BMN | Bouwmaterialen
Celsiusbaan 10 | 3439NC Nieuwegein

M +31 6 26760049
E fons.hofstra@bmn.nl<mailto:fons.hofstra@bmn.nl> | www.bmn.nl<http://www.bmn.nl>

KvK BMN Bouwmaterialen BV | 01013888

Twitter<https://twitter.com/BMN_Nederland> | Facebook<https://www.facebook.com/BMNNederland>

Houd rekening met het milieu. Print niet meer dan nodig is.

Van: Karthik [mailto:notifications@github.com]
Verzonden: vrijdag 25 januari 2019 10:49
Aan: Agence-DnD/PIMGento-2-API
CC: Hofstra, Fons; Mention
Onderwerp: Re: [Agence-DnD/PIMGento-2-API] Request-URI Too Long with product-import (#10)


Solution 1:
Increase the large_client_header_buffers in nginx.conf file http block,
large_client_header_buffers 4 16k;

Solution 2:
In my case I have around 700 families. In Akeneo API Configuration page I have choosen one family & excluded rest of the families in Filter Products section and try to import the product. It shows an error like Request-URI Too Long.

After debugging I figured it out the above issues is occured due to the excluded of families. Around 700 query parameters are passing when executing product import.

So the solution is while processing product import. If you have lot of families, exclude only less number of families.

Let me know if you have any questions

Regards,
Karthik Dhakshinamoorthy
