### ISSUE TITLE
category import not importing correctly

### ISSUE THREAD

**Issue by WhynachtVega** [Agence-DnD/PIMGento-2-API#100]
Hello,

When importing categories from akeneo we are facing an issue where after running the category import, it completes without recording any errors in the log. However
 category labels are not being imported at all.

![image](https://user-images.githubusercontent.com/48128806/54537095-ad0d3700-4970-11e9-9bf9-3436fbd2edc1.png)

**Environment**

Magento 2.3.0
Akeneo CE 3.0.7

**Comment by stefanfr** [comment]
@WhynachtVega I had this exact problem also. Make sure the locale within Akeneo is the same as Magento. In my case Magento was set to en_US and Akeneo to en_GB.

**Comment by akosglue** [comment]
I encountered the same problem, matching the locale's indeed helped.

**Comment by Dnd-Gimix** [comment]
Hello,

In addition, we have added a warning during the import process in order to inform users that labels are missing for categories or families.
I'll close this issue.

Regards,
