### ISSUE TITLE
Import Images

### ISSUE THREAD

**Issue by Johan-Hanekom** [Agence-DnD/PIMGento-2-API#109]
### Summary

1. Run all the import elements , everything (all categories, attributes, etc. import, but not images

### Expected result

1. Need to see the product image in Magento

### Actual result

1. Not seeing the image in Magento backend or frontend

**Comment by Dnd-Gimix** [comment]
Hello @Johan-Hanekom ,

As we have already solved this issue together, I'll close it.

Regards,
