### ISSUE TITLE
how we install the pimgento in our server

### ISSUE THREAD

**Issue by parveen12345** [Agence-DnD/PIMGento-2-API#114]
hello 
we want to install pimgento in our serve but how we install pimgento manually if we use composer it show error   "[Composer\Downloader\TransportException]
  Invalid credentials for 'https://repo.magento.com/packages.json', aborting."
please tell me how we install pimgento and how we configure to akeno

**Comment by parveen12345** [comment]
i am using  magento latest version 2.3.1

**Comment by Dnd-Gimix** [comment]
Hello @parveen12345 ,

Thank you for using PIMGento 2 API.
The error is not related to PIMGento, please make sure your Magento credentials are correct on your server.

After that, you can consult the documentation and follow the install steps : https://github.com/Agence-DnD/PIMGento-2-API/blob/master/doc/summary.md

Regards,

**Comment by parveen12345** [comment]
Thanks for the reply please tell me one thing we successful install the pimgento and then how we connect pimgento to akeneo and how we sync category and product from akeneo to Magento

**Comment by parveen12345** [comment]
hello we are facing this  problem please show the below error when we import product from akeneo to magento
product
[13:26:37] Start import
[13:26:37] Import ID : 5cbb1e0d59b1e
[13:26:37] Create temporary table
[13:26:37] Scope "http://134.209.47.176" does not exist.

**Comment by parveen12345** [comment]
products are not showing in frontend

**Comment by Dnd-Gimix** [comment]
Hello @parveen12345 ,

Did you managed to display your products ?

If not, please make sure to check the following steps:
-     Stock
-     Price
-     Visibility
-     Display rules in the catalog configuration
-     Category / website assignation
-     Indexes / Caches

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @parveen12345 ,

Without answer on this issue, I'll close it.
Feel free to open a new one if necessary.

Regards,
