### ISSUE TITLE
Regarding product is not visible in frontend

### ISSUE THREAD

**Issue by parveen12345** [Agence-DnD/PIMGento-2-API#117]
### Environment and configuration

1. 
2. 
3. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by parveen12345** [comment]
Hello,
we successfully import the product but when go into the frontend it show no product in product end .
when we check the url  http://165.227.217.192/catalog/category/view/s/cameras/id/46/
Is this url is correct or not .
please tell me the reson what is the issue 
we show this error:"We can't find products matching the selection."
plese help me its a very import for me please resply me as soon as possible.
Thanks
Parveen

**Comment by Zyles** [comment]
Did you enable the product and cleared caches?

**Comment by parveen12345** [comment]
Yes but tell me how we set all the product is  set quality to show all the products in front end

**Comment by Zyles** [comment]
> Yes but tell me how we set all the product is set quality to show all the products in front end

I don't really understand your english but make sure you have done all the things you need to make a product visible in Magento.

- Enable product = Yes/Green
- Put stock status "In stock"
- Add quantity above 0
- Assign product to a category
- Clear cache
- Rebuild index

**Comment by parveen12345** [comment]
Thanks it's working
