### ISSUE TITLE
Misspelling in di.xml configuration file - FamilyVariant steps wrongly enumerated?

### ISSUE THREAD

**Issue by smagdziarz** [Agence-DnD/PIMGento-2-API#120]
In the [etc/di.xml](https://github.com/Agence-DnD/PIMGento-2-API/blob/master/etc/di.xml) configuration file, in the section for FamilyVariant there are steps from 1 to 5 and then suddenly step 8.

```
<item name="8" xsi:type="array">
    <item name="method" xsi:type="string">cleanCache</item>
    <item name="comment" xsi:type="string">Clean cache</item>
</item>
```

Isn't this just a misspellnig and step 8 should be simply step 6?

```
<item name="6" xsi:type="array">
    <item name="method" xsi:type="string">cleanCache</item>
    <item name="comment" xsi:type="string">Clean cache</item>
</item>
```

**Comment by Dnd-Gimix** [comment]
Hello @smagdziarz ,

Thank you for using PIMGento 2 API !
The fix has been released in the new version https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.6.

Have a good day.

Regards,
