### ISSUE TITLE
Probleme dans la fonction setValues

### ISSUE THREAD

**Issue by alex5513** [Agence-DnD/PIMGento-2-API#122]
Bonjour,

Dans la méthode setValues() du job product, vous comparez l'attribut qui a été strtolower dans Magento avec l'attribut pas strtolower du PIM à la ligne 868. Du coup la valeur de l'attribut n'est pas importé.

Il y'a le même problème avec le job FamilyVariant à la ligne 74 dans updateAxis, en l'état les produits simples ne sont pas liés aux configurables si les attributs contiennent des majuscules dans Akénéo.

De manière générale je pense qu'il faudrait strtolower les codes d'attributs au moment de remplir les tables temporaires pour corriger tous les problemes.

Prévenez moi si vous faites une maj du module pour corriger ces points.

Cordialement

Alexis DURST

**Comment by Dnd-Gimix** [comment]
Bonjour Alexis,

Merci d'utiliser PIMGento 2 API !

Ces points ont été corrigés dans la release 100.2.6 : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.6

Peux-tu tester à nouveau et nous dire si tout est OK ?
En te souhaitant une bonne journée.

Cordialement,

**Comment by alex5513** [comment]
Bonjour Rémi,

Apparement c'est bon maintenant.

Merci pour l'évol'

Cordialement

Alexis

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513 ,

Merci pour ta confirmation, je ferme cette issue.

Cordialement,
