### ISSUE TITLE
Not compatible with M 2.3

### ISSUE THREAD

**Issue by sydekumf** [Agence-DnD/PIMGento-2-API#14]
### Environment and configuration
1. PHP 7.1 
2. Magento 2.3
3. PIMGento 2 API (newest version)

### Steps to reproduce
1. Import categories (or other entities)

### Expected result
1. Import sucessfully

### Actual result
1. An error appears: `[06:57:59] Notice: Undefined index: VARCHAR(255) NOT NULL DEFAULT "`

Background:
- In M 2.3 there is a new method in `Magento\Framework\DB\Adapter\Pdo\Mysql::addColumn()` which automatically parses the schema (SchemaListener), so you don't need to define it
- The PIMGento 2 API module allows working with M 2.3 (in composer.json)

**Comment by Dnd-Gimix** [comment]
Hi @sydekumf,

Thank you for using PIMGento2 API.

We are going to review your issue and test on our local environments with a Magento 2.3 version to deliver a fix.

We will come back to you once it's done.

Thanks again.
Regards,

**Comment by sydekumf** [comment]
Hi there,

thanks a lot. Can you maybe tell us when we can think of a fix for that? Will it take 1-2 weeks or maybe 1-2 months or more?
Just a rough clue, about when we can count with it, would be really helpful :-)

Thanks a lot!
