### ISSUE TITLE
Weak data validation while importing attributes

### ISSUE THREAD

**Issue by bartoszkubicki** [Agence-DnD/PIMGento-2-API#169]
It turned out that my installation of akeneo was broken, sth with database. However before discovering the issue with pim, I have already imported attributes, options and families. Pimgento didn't detected that my attribute data in pim is broken, so all custom imported attributes had backend type static (what means they require custom column in catalog_product_entity), and frontend_input was null (what broke product edit form). I doesn't really matter what was broken in pim instance, but the thing is that pimgento doesn't validates incoming data, what in production env can cause serious disaster.

### Environment and configuration

1. Pimgento 100.2.7

### Steps to reproduce

It maybe be hard to reporoduce, because it kind of general issue. I think one should mess sth in akaneo db and test if import validates data while importing.

### Expected result

1. Imported data is validated accurately
2. No broken attributes info is imported
3. There is info which one is broken, and what exactly is to be fixed.

### Actual result

1. Broken data is imported without any notice.

**Comment by Dnd-Gimix** [comment]
Hello,

As announced on July 25, the repository PIMGento 2 API will be closed by the end of next week. 
Please make sure to check the new connector "Akeneo Connector for Magento 2", available on the Akeneo Github at this address : https://github.com/akeneo/magento2-connector-community

We took note of your issue and we will make sure to provide a fix if necessary on the new version of the connector.

Thank you for your contribution on this repository, we hope to see you back on the new repository !

Have a good day.

Regards,

**Comment by bartoszkubicki** [comment]
Do I have to migrate all submitted issues to the new repository? (it is still present on the newest version of connector)

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

If the issues are still relevant on the new repository, you can migrate them to the new repository ;)

Have a good day !

Regards,

**Comment by bartoszkubicki** [comment]
migrated.
