### ISSUE TITLE
Poor extensibility of pimgento jobs

### ISSUE THREAD

**Issue by bartoszkubicki** [Agence-DnD/PIMGento-2-API#170]
In order to add any new step to Jobs, for example Product Import there is no easy way, because of strange import class configuration.
In [here](https://github.com/Agence-DnD/PIMGento-2-API/blob/08316ed71436a8aa0ed24b645d9cd55e430a1b53/Job/Import.php#L378), there is strange call, which performs all operation for import. In config file [here](https://github.com/Agence-DnD/PIMGento-2-API/blob/08316ed71436a8aa0ed24b645d9cd55e430a1b53/etc/di.xml#L277) there are all methods defined, which are called later in above class. It means, that if we want to add custom step, for importing custom data from akeneo, we have to directly override class specified in `di.xml` instead of extending its functionality via composition.

Side note - current solution makes parent class [Import](https://github.com/Agence-DnD/PIMGento-2-API/blob/master/Job/Import.php) depending on its children/implementation, because we call not existing methods from inheriting classes.

### Environment and configuration

1. Pimgento 100.2.7

### Expected result

1. Create new module dependant on Pimgento API module
2. In `di.xml` we inject into original Pimgento class our class doing something during import. It should implement some interface to make it work, no matter of implemenetation.
3. Import grabs our additional step and processes it, the same way, how it treats default steps.

### Actual result

1. There is no clear way, but the easiest (it doesn't mean it' elegant and clean) is extending whole job class and inject it instead of Pimgento.
2. In class extending default job class we add methods needed, as they have to be called in scope of `$this`.

**Comment by Dnd-Gimix** [comment]
Hello,

As announced on July 25, the repository PIMGento 2 API will be closed by the end of next week. 
Please make sure to check the new connector "Akeneo Connector for Magento 2", available on the Akeneo Github at this address : https://github.com/akeneo/magento2-connector-community

We took note of your issue and we will make sure to provide a fix if necessary on the new version of the connector.

Thank you for your contribution on this repository, we hope to see you back on the new repository !

Have a good day.

Regards,

**Comment by bartoszkubicki** [comment]
Do I have to migrate all sumbitted issues to the new repository? (it is still present on the newest version of connector)

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

If the issues are still relevant on the new repository, you can migrate them to the new repository ;)

Have a good day !

Regards,

**Comment by bartoszkubicki** [comment]
migrated
