### ISSUE TITLE
Attributes with source model still get new options from Akeneo

### ISSUE THREAD

**Issue by bartoszkubicki** [Agence-DnD/PIMGento-2-API#171]
It is quite edge case, but it sometimes occurs. While having attribute in magento with source model bound, and corresponding one with options in akeneo, we stilll got these options imported as eav options. It occurs for example if we create `tax_class_id`. Its options from akeneo are inserted into `eav_attribute_option_*` tables. There is no validation that attribute has source model. On the other hand it doesn't seem to break anything, but it is confusing.

### Environment and configuration

1. Pimgento 100.2.7

### Steps to reproduce

1. Add attribute in akeneo which have source model in magento or modify magento attribute, so it works basing on source model
2. Add some options in akeneo
3. Import options in magento

### Expected result

1. No new rows in eav options tables = no rubbish in db.
2. Info about difference in options source, so merchant or developer can fix that .

### Actual result

1. New rows in eav options tables for this attribute, despite the fact it doesnt use options
2. No info what happened.

**Comment by Dnd-Gimix** [comment]
Hello,

As announced on July 25, the repository PIMGento 2 API will be closed by the end of next week. 
Please make sure to check the new connector "Akeneo Connector for Magento 2", available on the Akeneo Github at this address : https://github.com/akeneo/magento2-connector-community

We took note of your issue and we will make sure to provide a fix if necessary on the new version of the connector.

Thank you for your contribution on this repository, we hope to see you back on the new repository !

Have a good day.

Regards,

**Comment by bartoszkubicki** [comment]
Do I have to migrate all submitted issues to the new repository? (it is still present on the newest version of connector)

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

If the issues are still relevant on the new repository, you can migrate them to the new repository ;)

Have a good day !

Regards,

**Comment by bartoszkubicki** [comment]
migrated
