### ISSUE TITLE
Error when trying to import products

### ISSUE THREAD

**Issue by sahilgoyal786** [Agence-DnD/PIMGento-2-API#18]
product
[20:21:07] Start import
[20:21:07] Import ID : 5bde0333cfd7f
[20:21:07] Create temporary table
[20:21:10] completed
[20:21:10] Fill temporary table
[20:21:12] Property "completeness" expects a valid scope.

**Comment by JelleGroenendal** [comment]
You need to configure the mapping of the website in the Pimgento store configuration

**Comment by sahilgoyal786** [comment]
on Magento end or akeneo end?

**Comment by JelleGroenendal** [comment]
At the Magento end.
For example you can map the websites / storeviews in the configuration of Pimgento.
For a default Akeneo installation the channel will probably be ecommerce.
So example.com can be mapped to ecommerce.
This can be done in Store -> Configuration -> Catalog -> Pimgento: Akeneo API Configuration -> Website mapping.
