### ISSUE TITLE
Configurable products are not imported correctly 

### ISSUE THREAD

**Issue by markdooremaal** [Agence-DnD/PIMGento-2-API#25]
When I import my products the different variant products will import correctly as simple products but pimgento will create 2 configurable products both not containing the right amount of variants.

### Environment and configuration

1. Magento 2.2.6
2. Akeneo  2.3.16 
3. PIMgento2 (API)
4. PHP 7.1.23
5. MySQL 5.7.24
6. [Valet+](https://github.com/weprovide/valet-plus)
7. MacOS 10.14.1

### Steps to reproduce

1. Add a 2 axis variant to a family
2. Create a product based on that family
3. Fill the product (I added two level 1 axis with both two level 2 axis)
![afbeelding](https://user-images.githubusercontent.com/17912991/48546386-85299c00-e8c8-11e8-9012-7e49a1075bf1.png)

![afbeelding](https://user-images.githubusercontent.com/17912991/48546409-9672a880-e8c8-11e8-9f42-d49e8ec8e0be.png)

4. Export the product using Pimgento to Magento

### Expected result

1. 1 configurable product with all the different variants. Like how it is shown in Akeneo
![afbeelding](https://user-images.githubusercontent.com/17912991/48546527-e05b8e80-e8c8-11e8-8e50-3d4a40fcf132.png)

### Actual result

1. Two different configurable products within magento.
![afbeelding](https://user-images.githubusercontent.com/17912991/48547007-f584ed00-e8c9-11e8-8cfc-88418d76b160.png)
2. The configurable product with SKU buxus_kluit only includes one of the two simple products.

**Comment by magentix** [comment]
Hi,

Indeed, actually 2 levels variant create 2 configurables instead 1 in Magento.

We work to fix this quickly.

Regards,
Matthieu

**Comment by magentix** [comment]
Hi,

A Pull Request has been added:

https://github.com/Agence-DnD/PIMGento-2-API/pull/38

This issue will be fix in next release.

Regards,
Matthieu

**Comment by markdooremaal** [comment]
Hi, @magentix 

I tested  #38 and this fixed my issue. 
Thanks for the help!

**Comment by Dnd-Gimix** [comment]
Hi @markdooremaal ,

Glad it fixed your issue.
Have a nice day.

Regards,
