### ISSUE TITLE
Error when importing products

### ISSUE THREAD

**Issue by TVO99** [Agence-DnD/PIMGento-2-API#26]
Hi,

When I try to import products from Akeneo 2.3.6 (using the magento admin interface), I'm getting this error:
All the previous steps worked fine (importing categories, families, attributes...)

product
[17:27:16] Start import
[17:27:16] Import ID : 5bedac747edef
[17:27:16] Create temporary table
[17:27:16] Notice: Undefined offset: 0 in /var/www/html/magento2/vendor/agencednd/module-pimgento-2-api/Helper/Import/Product.php on line 132

**Environment and configuration**
Magento 2.2.6 CE installed using composer, on Linux Ubuntu 18.04.1 LTS

**Comment by TVO99** [comment]
Hi, 

We are using a stock Akeneo installation, no customization at all. 
And yes, we are using multiselect attributes in viarious places: 

Example: 






Van: "Rémi Verrière" <notifications@github.com> 
Aan: "Agence-DnD/PIMGento-2-API" <PIMGento-2-API@noreply.github.com> 
Cc: "tom" <tom.van.overbeke@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Vrijdag 16 november 2018 10:28:01 
Onderwerp: Re: [Agence-DnD/PIMGento-2-API] Error when importing products (#26) 



Hi [ https://github.com/TVO99 | @TVO99 ] , 

Thank you for using PIMGento2 API. 

This error seems to happen during a multiselect attribute data parsing. 
Could you provide us more details about your Akeneo integration ? Any customization on Akeneo side ? 

Are you using multiselect attributes on Akeneo ? 

Thanks again. 

Regards,

**Comment by Dnd-Gimix** [comment]
@TVO99 ,

A cannot see your attached files.
Could you please re-upload them ?

Thank you.

Regards,

**Comment by TVO99** [comment]
Hi, 

is this better? 




Van: "Rémi Verrière" <notifications@github.com> 
Aan: "Agence-DnD/PIMGento-2-API" <PIMGento-2-API@noreply.github.com> 
Cc: "tom" <tom.van.overbeke@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Vrijdag 16 november 2018 13:00:53 
Onderwerp: Re: [Agence-DnD/PIMGento-2-API] Error when importing products (#26) 



[ https://github.com/TVO99 | @TVO99 ] , 

A cannot see your attached files. 
Could you please re-upload them ? 

Thank you. 

Regards,

**Comment by Dnd-Gimix** [comment]
@TVO99 ,

Unfortunetly no :/
Can you post your comment directly from the Github interface please ?

Thanks.

Regards,

**Comment by TVO99** [comment]
Hi,
here's the screenshot:
![knipsel](https://user-images.githubusercontent.com/43167260/48624948-17f03680-e9ae-11e8-9c8a-4f13e9cb93b9.PNG)

**Comment by TVO99** [comment]
Hi, 

I just added it via github. 



Van: "Rémi Verrière" <notifications@github.com> 
Aan: "Agence-DnD/PIMGento-2-API" <PIMGento-2-API@noreply.github.com> 
Cc: "tom" <tom.van.overbeke@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Vrijdag 16 november 2018 13:46:49 
Onderwerp: Re: [Agence-DnD/PIMGento-2-API] Error when importing products (#26) 



[ https://github.com/TVO99 | @TVO99 ] , 

Unfortunetly no :/ 
Can you post your comment directly from the Github interface please ? 

Thanks. 

Regards,

**Comment by TVO99** [comment]
Hi,
Do you need further info from me to speed up the bug investigation?

**Comment by magentix** [comment]
Hi @rakibabu ,

PR is validated and will be merged.

Thanks for contribution 🥇

**Comment by Dnd-Gimix** [comment]
Hi @TVO99 , @rakibabu ,

Fix has been applied in the new release 100.1.2.
Thank you for your contribution !

Have a good day.

Regards,
