### ISSUE TITLE
When is `_is_new`= 1?

### ISSUE THREAD

**Issue by sydekumf** [Agence-DnD/PIMGento-2-API#29]
It is not a bug report, but more a question, as I can not find any documentation or help. The `_is_new` field is default set to `0` in `tmp_pimgento_entities_family`. Who or what does it set to `1`? Is it from the Akeneo API? What should be set there so that entites are again new?

The problem is:
On one system everything works, if you import a second time on another system, the data is broken, as the entities are not longer new. The module differentiates several times for is_new or not during importing the data.

Thanks for help!

**Comment by magentix** [comment]
Hi,

```_is_new``` is set to 1 when entity imported is not yet in Magento.

Column is set to 1 after entity matching for new entities.

Regards,
Matthieu

**Comment by Dnd-Gimix** [comment]
Hi @sydekumf ,

Do you need any additional informations on that subject ?

Regards,

**Comment by sydekumf** [comment]
Thanks! It is clear to me :-)
