### ISSUE TITLE
Product Import: pimgento_product_model table doesn't exist

### ISSUE THREAD

**Issue by NirmalRaval** [Agence-DnD/PIMGento-2-API#30]
As per the issue mentioned in previous ticket #172, I am still facing the same issue even though I have downloaded the latest zip from site just 4 days back.

Here is the details of my Issue, I have tried to import products from Akeneo to Magento after configuring successfully.

It throws following error while importing.

> product
> [08:57:49] Start import
> [08:57:49] Import ID : 5bf3cc8d847db
> [08:57:49] Create temporary table
> [08:57:56] completed
> [08:57:56] Fill temporary table
> [08:58:02] 0 line(s) found
> [08:58:02] Add required data
> [08:58:02] completed
> [08:58:02] Create configurables
> [08:58:03] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mwh_magento2_new.pimgento_product_model' doesn't exist, query was: INSERT INTO `tmp_pimgento_entities_product` (`identifier`, `url_key`, `_children`, `_type_id`, `_options_container`, `_status`, `_axis`, `family`, `categories`) SELECT `e`.`parent` AS `identifier`, `e`.`parent` AS `url_key`, GROUP_CONCAT(e.identifier SEPARATOR ",") AS `_children`, "configurable" AS `_type_id`, "container1" AS `_options_container`, `e`.`_status`, `v`.`axis` AS `_axis`, `e`.`family`, `e`.`categories` FROM `tmp_pimgento_entities_product` AS `e` INNER JOIN `pimgento_product_model` AS `v` ON e.parent = v.code WHERE (e.parent <> "") GROUP BY `e`.`parent`

I have also attached screenshot of same error.

We have table prefix in database. Pimgento tables are also created with this table prefix. But when it tries to import the data it does not take the table name with its prefix.

We have an urgent requirement to configure this extension with magento and run successfully.

Urgent help will be more useful.
![pimgento product import](https://user-images.githubusercontent.com/30285726/48763766-f5269080-ecd3-11e8-9d0f-4d32192cd1c9.png)

**Comment by Dnd-Gimix** [comment]
Hello @NirmalRaval ,

Thank you for using PIMGento2 API.

Could you try to follow these steps : 
- php bin/magento setup:db:status
- php bin/magento setup:upgrade
- php bin/magento cache:flush

Can you tell me what is your database prefix ?

Thank you.
Regards,

**Comment by NirmalRaval** [comment]
Hello,

I have tried all the above setps but it did not worked for me.

database table prefix is 'dev_'

Let me know if any other details needed.

**Comment by NirmalRaval** [comment]
Hello,

We have added table prefix manually in your extension code in our project.

So the table not found issue got resolved for us as of now.

Now we are getting Foreign Key constraints issue while importing Category and Product.

Here is the error that I am getting while import.

Category Import:

> category
> [14:03:41] Start import
> [14:03:41] Import ID : 5bf4143d756b8
> [14:03:41] Create temporary table
> [14:03:47] completed
> [14:03:47] Fill temporary table
> [14:03:54] 103 line(s) found
> [14:03:54] Match code with Magento ID
> [14:03:54] completed
> [14:03:54] Create URL key
> [14:03:55] completed
> [14:03:55] Create structure
> [14:03:55] completed
> [14:03:55] Create position
> [14:03:56] completed
> [14:03:56] Create and update category entities
> [14:03:56] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mwh_magento2_new`.`dev_catalog_category_entity`, CONSTRAINT `CAT_CTGR_ENTT_ENTT_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL` FOREIGN KEY (`entity_id`) REFERENCES `dev_sequence_catalog_category` (`seque), query was: INSERT INTO `dev_catalog_category_entity` (`entity_id`, `attribute_set_id`, `parent_id`, `updated_at`, `path`, `position`, `level`, `children_count`, `row_id`) SELECT `tmp_dev_pimgento_entities_category`.`_entity_id` AS `entity_id`, 3 AS `attribute_set_id`, `tmp_dev_pimgento_entities_category`.`parent_id`, now() AS `updated_at`, `tmp_dev_pimgento_entities_category`.`path`, `tmp_dev_pimgento_entities_category`.`position`, `tmp_dev_pimgento_entities_category`.`level`, 0 AS `children_count`, `tmp_dev_pimgento_entities_category`.`_entity_id` AS `row_id` FROM `tmp_dev_pimgento_entities_category` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_set_id` = VALUES(`attribute_set_id`), `parent_id` = VALUES(`parent_id`), `updated_at` = VALUES(`updated_at`), `path` = VALUES(`path`), `position` = VALUES(`position`), `level` = VALUES(`level`), `children_count` = VALUES(`children_count`), `row_id` = VALUES(`row_id`)

Product Import

> product
> [14:33:39] Start import
> [14:33:39] Import ID : 5bf41b431e9d7
> [14:33:39] Create temporary table
> [14:33:45] completed
> [14:33:45] Fill temporary table
> [14:33:51] 0 line(s) found
> [14:33:51] Add required data
> [14:33:51] completed
> [14:33:51] Create configurables
> [14:33:52] completed
> [14:33:52] Match code with Magento ID
> [14:33:52] completed
> [14:33:52] Match family code with Magento ID
> [14:33:53] completed
> [14:33:53] Update column values for options
> [14:33:53] completed
> [14:33:53] Create or update product entities
> [14:33:54] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mwh_magento2_new`.`dev_catalog_product_entity`, CONSTRAINT `CATALOG_PRODUCT_ENTITY_ENTITY_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE` FOREIGN KEY (`entity_id`) REFERENCES `dev_sequence_product` (`seq), query was: INSERT INTO `dev_catalog_product_entity` (`entity_id`, `attribute_set_id`, `type_id`, `sku`, `has_options`, `required_options`, `updated_at`, `row_id`) SELECT `tmp_dev_pimgento_entities_product`.`_entity_id` AS `entity_id`, `tmp_dev_pimgento_entities_product`.`_attribute_set_id` AS `attribute_set_id`, `tmp_dev_pimgento_entities_product`.`_type_id` AS `type_id`, `tmp_dev_pimgento_entities_product`.`identifier` AS `sku`, 0 AS `has_options`, 0 AS `required_options`, now() AS `updated_at`, `tmp_dev_pimgento_entities_product`.`_entity_id` AS `row_id` FROM `tmp_dev_pimgento_entities_product` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_set_id` = VALUES(`attribute_set_id`), `type_id` = VALUES(`type_id`), `sku` = VALUES(`sku`), `has_options` = VALUES(`has_options`), `required_options` = VALUES(`required_options`), `updated_at` = VALUES(`updated_at`), `row_id` = VALUES(`row_id`)

Let me know if you can help us out in this.

**Comment by Dnd-Gimix** [comment]
@NirmalRaval : We have been able to reproduce the issue on a local environment.
We are currently working on a fix for the issue.

Regards,

**Comment by Dnd-Gimix** [comment]
@NirmalRaval ,

The prefix issue has been fixed by @magentix on https://github.com/Agence-DnD/PIMGento-2-API/pull/31.
This fix is supposed to also handle your second error message.

Could you please try again with the changes from the PR ?

Thanks.
Regards,

**Comment by NirmalRaval** [comment]
Hello,

Sure, let me check and update you soon on this.

Thanks.

**Comment by NirmalRaval** [comment]
Hello,

I have added the fix to our project and both the error has been solved now.

After that I have tried to import one product by adding filter in product from magento admin and executed product import.

It ran successfully but New Product created instead of updating the same product from Akeneo.

We need to create the Product/Category/Family/Attribute only if it is not there in magento otherwise it should be updated in it.

Kindly explain us the scenario how this will work with Pimgento extension.

Thanks.

**Comment by Dnd-Gimix** [comment]
Hello @NirmalRaval ,

The fix for Magento prefixed table is now released in the new 100.1.2 version.

As discussed by e-mail regarding the update of your products : 

- You can't update products that have not been imported with the connector
- PIMGento needs the link created during import to match with your products in Magento so if the link is missing, it will create new product instead of updating the existing one
- The best way to setup PIMGento is to start from an empty product database

I am closing this issue, thank you for your feedback !
Have a good day.

Regards,
