### ISSUE TITLE
Products added to All Websites

### ISSUE THREAD

**Issue by wgriffiths** [Agence-DnD/PIMGento-2-API#41]
We have setup multiple channels in Akeneo and multiple website in Magento. Products are only in one channel in Akeneo, but when we import them into Magento they are available on all websites. Is there a way of restricting the websites a product is on based on the akeneo to magento mapping?

From the code it looks like it will always set a product to be available on all websites, or have I missed something? 

**Pimgento\Api\Job\Product:setWebsites()**
```php
    foreach ($websites as $websiteId => $affected) {
            if ($websiteId == 0) {
                continue;
            }

            /** @var Select $select */
            $select = $connection->select()->from(
                    $tmpTable,
                    [
                        'product_id' => '_entity_id',
                        'website_id' => new Expr($websiteId),
                    ]
                );

            $connection->query(
                $connection->insertFromSelect(
                    $select,
                    $this->entitiesHelper->getTable('catalog_product_website'),
                    ['product_id', 'website_id'],
                    AdapterInterface::INSERT_ON_DUPLICATE
                )
            );
        }
```

**Comment by magentix** [comment]
Hi wgriffiths,

Indeed, products are setted on all website. We look for assign product only on correct website.

Regards,
matthieu

**Comment by zelgerj** [comment]
Hi @magentix,

perfekt! What about the timing of this enhancement?

Thanks!

Best regards,
Johann

**Comment by Dnd-Gimix** [comment]
Hello @zelgerj , @wgriffiths ,

We have released a new version of the connector (100.2.1), containing the fix to assign products only to the mapped websites in PIMGento2 API configuration.
Also, you'll find a new configuration to assign the channel you want to retreive values from for the admin website : you'll need to fill this configuration in order to launch your imports.

Could you come back to me to confirm that the new version resolved your issue ?

This release is containing multiple improvements that you'll find in our changelog : https://github.com/Agence-DnD/PIMGento-2-API/blob/master/CHANGELOG.md

Regards,

**Comment by wgriffiths** [comment]
Thanks @Dnd-Gimix  I will test the release and let you know

**Comment by Dnd-Gimix** [comment]
Hello @zelgerj , @wgriffiths ,

Have you been able to test the new release that fix product website assignation ?

Regards,

**Comment by wgriffiths** [comment]
@Dnd-Gimix I have tested it and It didn't seem to work. I think it because I didn't clear out my catalog_product_website. I am clearing out all my product data and giving it another go. Apologies for the delay in verifying the fix

**Comment by zelgerj** [comment]
@Dnd-Gimix ,

looks good! Thanks for keeping us on track!
I very appreciate that :+1:

Best Regards,
Johann

**Comment by Dnd-Gimix** [comment]
Hello @wgriffiths ,

No problem, thank you for the answer. Is everything good after deleting the catalog_product_website content ?

Hello @zelgerj ,

Thank you for your answer, glad it worked !

Have a good day.
Regards,

**Comment by Dnd-Gimix** [comment]
Hello @wgriffiths ,

I assume that if the fix worked for @zelgerj , it should work for you too after deleting the catalog_product_website content ;)

I'll close this issue, thank you all for the tests and feedbacks.
Feel free to open a new issue if needed !

Have a good day.

Regards

**Comment by wgriffiths** [comment]
Thanks @Dnd-Gimix
