### ISSUE TITLE
Build fails with clean database

### ISSUE THREAD

**Issue by simonmaass** [Agence-DnD/PIMGento-2-API#45]
Patch:

Index: Console/Command/PimgentoImportCommand.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Console/Command/PimgentoImportCommand.php	(date 1543840719000)
+++ Console/Command/PimgentoImportCommand.php	(date 1543840719000)
@@ -7,7 +7,7 @@
 use Magento\Framework\Data\Collection;
 use Magento\Framework\Exception\LocalizedException;
 use Magento\Framework\Phrase;
-use Pimgento\Api\Api\ImportRepositoryInterface;
+use Pimgento\Api\Api\ImportRepositoryInterface\Proxy as ImportRepositoryInterface;
 use Pimgento\Api\Job\Import;
 use \Symfony\Component\Console\Command\Command;
 use \Symfony\Component\Console\Input\InputInterface;

**Comment by DnD-Hellion** [comment]
Hi @simonmaass ,

Thank you for using Pimgento 2 API.

Could you give us more details on the issue you have?
Is your Magento already installed or did you start with a fully empty database?

We will look into this, but we need to create test conditions similar to your environment settings.

Looking forward to reading you.

Regards,

PS: Do not hesitate to create Pull Requests. ;)

**Comment by simonmaass** [comment]
we have a build that runs over circleci and compiles the whole project - there the process fails but gets fixed with the patch that i posted...

in file: Console/Command/PimgentoImportCommand.php
-use Pimgento\Api\Api\ImportRepositoryInterface;
+use Pimgento\Api\Api\ImportRepositoryInterface\Proxy as ImportRepositoryInterface;

**Comment by Dnd-Gimix** [comment]
Hello @simonmaass ,

New release 100.2.6 is out containing the fix for proxy class : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.6

I'll close this issue.

Regards,
