### ISSUE TITLE
Compatibility Magento 2.3?

### ISSUE THREAD

**Issue by simonmaass** [Agence-DnD/PIMGento-2-API#51]
Any info on Magento 2.3 compatibility?

**Comment by sydekumf** [comment]
There is already a release for that.

**Comment by simonmaass** [comment]
in composer:    "php": "~5.6.0|~7.0.0|~7.1.0",

magento 2.3 has 7.2...

**Comment by sydekumf** [comment]
Magento 2.3 runs on PHP 7.1

**Comment by simonmaass** [comment]
well does pimgento support php7.2?

**Comment by Dnd-Gimix** [comment]
Hello @simonmaass , @sydekumf ,

We have added PHP 7.2 compatibility in the 100.1.4 release.
Have a good day !

Regards,
