### ISSUE TITLE
Error in importing currency and convert group in Akeneo to attribute in Magento

### ISSUE THREAD

**Issue by MsEngineer** [Agence-DnD/PIMGento-2-API#55]
Unable to import prices in correct currency.
Magento multi-websites but unique webstore/catalogue and multiple currencies.
Akeneo unique channel multiple languages and currencies.
The problem is that Pimgento only import the first price in Akeneo and does not upload each price for each currency.
Also, the brand in Magento is an attribute but is a group in Akeneo. I need to import the brand in Magento. How can I configure that?

### Environment and configuration

1. Magento OS 2.2.7
2. Akeneo CE 2.3.15
3. PHP 7.1.2 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. I should be able to receive in Magento the price in each currency and receive the brand as well.

### Actual result

1. Right now, Magento only receives the first price in Akeneo and applies it.
2. Magento is unable to receive the brand as an attribute

**Comment by JelleGroenendal** [comment]
https://github.com/Agence-DnD/PIMGento-2-API/pull/53 solves this i believe.

**Comment by Dnd-Gimix** [comment]
Hello @MsEngineer ,

Thank you for using PIMGento 2 API.

We have just released the new 100.2.2 version of the connector, including a fix for price and currency issues, and more globally a refactor for value assignation regarding attribute scopes in Magento.

Could you upgrade your connector to the latest version and try again please ?
Also, if possible, make sure to clean the old data before importing to prevent any side effect or unwanted behavior from previous imports.

Thank you.
Regards,

**Comment by Dnd-Gimix** [comment]
@MsEngineer ,

Regarding the second question : _Also, the brand in Magento is an attribute but is a group in Akeneo. I need to import the brand in Magento. How can I configure that?_

At this time, PIMGento 2 API is not importing Akeneo groups as it has no equivalent on Magento side.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @MsEngineer ,

Any news on the testing of this issue ?

Regards,

**Comment by MsEngineer** [comment]
Bonjour,
 J'ai dû complètement enlever votre extension car ça m'a créé beaucoup de problèmes dans ma base de données Magento.

-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 28/03/2019, 12:51 "Rémi Verrière" <notifications@github.com> wrote:
Hello @MsEngineer ,
Any news on the testing of this issue ?
Regards,

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Agence-DnD/PIMGento-2-API","title":"Agence-DnD/PIMGento-2-API","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Agence-DnD/PIMGento-2-API"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dnd-Gimix in #55: Hello @MsEngineer ,\r\n\r\nAny news on the testing of this issue ?\r\n\r\nRegards,"}],"action":{"name":"View Issue","url":"https://github.com/Agence-DnD/PIMGento-2-API/issues/55#issuecomment-477581524"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Agence-DnD/PIMGento-2-API/issues/55#issuecomment-477581524",
"url": "https://github.com/Agence-DnD/PIMGento-2-API/issues/55#issuecomment-477581524",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Dnd-Gimix** [comment]
@MsEngineer ,

Entendu, merci pour votre retour.
Je ferme cette issue.

En vous souhaitant une bonne journée.

Cordialement,
