### ISSUE TITLE
Issue Importing Prices with the connector from Akeneo to Magento

### ISSUE THREAD

**Issue by davidselo** [Agence-DnD/PIMGento-2-API#56]
An issue found with prices imported from Akeneo to Magento. 

### Environment and configuration

1. Magento 2.3
2. Akeneo 2.3.17 
3. PIMGento2 (API) 
4. Akeneo Sample Data. 

### Summary of the issue

An issue has been found in the process of importing the product catalog from Akeneo to Magento. 

There are two scenarios

1. Product in Akeneo doesn't have a price: Then the connector import the product with the price to zero for store and website scope. Then when you try to change the price manually into Magento it doesn't work. The price shouldn't be imported by store scope. 

2. Product price in Akeneo is not empty:  it looks like is working in the frontend because the prices are correct the first time you import, but if you go to analyze the data into the database, the connector has included the price by store and global scope. If you change the price in Magento backend it doesn't take it into account. 

### Steps to reproduce
Scenario 1: 

* Given I have imported Akeneo sample data into Magento 
* * And the product hasn't a price in akeneo
* When  I change the price into Magento
* Then it is always zero.

Scenario 2: 

* Given I have imported Akeneo sample data into Magento 
* * And the product has a price in akeneo
* When  I change the price into Magento
* Then It doesn't change the price. 

### Expected result
Price changes remain after you change it in Magento backend and price is saved into the database for Global scope

### Actual result

Product in Akeneo: 
![akeneo information](https://user-images.githubusercontent.com/983272/50165055-031fff00-02dc-11e9-8d56-e33e734378ff.png)

Product in Magento after the import process: 
![product magento backend](https://user-images.githubusercontent.com/983272/50165088-1206b180-02dc-11e9-82e6-138a1d095d17.png)

You change the price: 
![product page](https://user-images.githubusercontent.com/983272/50165238-6dd13a80-02dc-11e9-9f48-9f6a24840478.png)
![product price changed](https://user-images.githubusercontent.com/983272/50165142-31054380-02dc-11e9-893c-0db670083676.png)

Category Page(after changing the price):
![product category page](https://user-images.githubusercontent.com/983272/50165206-5a25d400-02dc-11e9-8046-f7b7b5a7f3ed.png)

Product Page( after changing the price): 
![product page](https://user-images.githubusercontent.com/983272/50165255-77f33900-02dc-11e9-8d1f-ad57fe8acbfb.png)

The result of Table catalog_product_entity_decimal: 
![how is saved on the database](https://user-images.githubusercontent.com/983272/50165293-8ccfcc80-02dc-11e9-8cce-fb5f04897242.png)

**Comment by Dnd-Gimix** [comment]
Hello @davidselo , @jonfres ,

The first issue has been resolved with the new version 100.2.1 of the connector : 
> _Product in Akeneo doesn't have a price: Then the connector import the product with the price to zero for store and website scope. Then when you try to change the price manually into Magento it doesn't work. The price shouldn't be imported by store scope._

We are currently working on the scope issue and we will provide a fix for this one soon.

This release is containing multiple improvements that you'll find in our changelog : https://github.com/Agence-DnD/PIMGento-2-API/blob/master/CHANGELOG.md

Make sure to check the new configuration fields after update ;)

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @davidselo , @jonfres ,

We have just released the new 100.2.2 version of the connector, including the global refactor for value assignation regarding attribute scopes in Magento.
This release should fix all your prices issues.

Could you upgrade your connector to this version and try again please ?

Also, if possible, make sure to clean the old data before importing to prevent any side effect or unwanted behavior from previous imports.

Thank you.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @davidselo , @jonfres ,

Any news on the testing of this issue ?

Regards,

**Comment by davidselo** [comment]
Good Afternoon, 

Thanks for fixing the issue, I am sorry to tell you that we ended using a different Module integration. 

If we use your module again I will let you know. 

Thanks, 
David

**Comment by Dnd-Gimix** [comment]
Thank you @davidselo for your feedback.

Regards,
