### ISSUE TITLE
Feature questions (configurables, product websites, attribute scope)

### ISSUE THREAD

**Issue by sydekumf** [Agence-DnD/PIMGento-2-API#57]
Hi there,

we think Pimgento is a very nice structured module to import products from Akeneo to Magento. But we encountered three problems which we are kind of surprised, how Pimgento handles them:

- We have a configurable on 3 levels in Akeneo, i.e. a T-Shirt with color and size:
![bildschirmfoto 2018-12-20 um 16 51 03](https://user-images.githubusercontent.com/3983052/50295088-95a8d580-0477-11e9-806f-36ca2ce1c4e7.png)
Suppose you have 2 colors and each has 6 sizes. This leads to 2 configurables in Magento each having 6 simples. We expected to have 1 configurable with 12 simples. Can you help us clarifying how that should be handled? We expected Pimgento to import it like that.
- Independently from channel assignment in Akeneo, the products get assigned to all available websites in Magento. We have multi website setup in Magento and need to diversify the products to the websites. Will this be implemented by Pimgento soon? What are the plans?
- We need to have attribute data (i.e. price) which is configured on a channel scope to be different in Magento websites. That means: Price in Channel A is 10€, in Channel B it is 15€ for the same product. We expect that the product's price is in Website A 10€ and in Website B it is 15€. Our tests showed this is not possible today. Any solution to that?

If we miss understood some configuration or the functionality of Pimgento it would be very helpful if you guide us what we did wrong. If this is not yet implemented, we would really appreciate some insights in your roadmap as we need it for our projects. Are there any plans that you might implement this?

Any information about that would really help us, thanks a lot guys :-) You already did an awesome job with this module :-)

**Comment by sydekumf** [comment]
Hi there,

I just found out that problem 1 was already fixed in https://github.com/Agence-DnD/PIMGento-2-API/pull/38

So only problem 2 and 3 are relevant for us :-)

**Comment by Dnd-Gimix** [comment]
Hello @sydekumf ,

Thank you for your interest in PIMGento 2 API.
I confirm you that the first problem has already been resolved.

The new version 100.2.1 is out and fix the website assignation issue.

Regarding the third issue, we are aware of this problem and we are currently working on a fix. We will come back to you once it is available.

This release is containing multiple improvements that you'll find in our changelog : https://github.com/Agence-DnD/PIMGento-2-API/blob/master/CHANGELOG.md

Make sure to check the new configuration fields after update ;)

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @sydekumf  ,

Have you been able to test the new release that fix product website assignation ?

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @sydekumf ,

We have just released the new 100.2.2 version of the connector, including the global refactor for value assignation regarding attribute scopes in Magento.
This release should fix your last price issue.

Could you upgrade your connector to this version and try again please ?

Also, if possible, make sure to clean the old data before importing to prevent any side effect or unwanted behavior from previous imports.

Have you been able to test the website assignation yet ?

Thank you.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @sydekumf ,

**Comment by sydekumf** [comment]
Sorry, we already fixed the website mapping on our own.
