### ISSUE TITLE
API Settings not Displayed

### ISSUE THREAD

**Issue by gconstable** [Agence-DnD/PIMGento-2-API#58]
Hi, I am after some support please.

I have attempted to install Pimgento-2-API twice now using your instructions with no luck.

Everything appears to install fine with no errors, however, when attempting to configure the API settings under

Configure your API settings in "Store > Configuration > Catalog > Pimgento"

i receive a blank screen with no options over than the menu.   The developer console also displayers no errors within the browsers.

I am using magento CE 2.3

Many Thanks

**Comment by gconstable** [comment]
This has been resolved.  It turned out to be an issue with the magento installation and not the pimgento installation.

**Comment by daveaie** [comment]
Hi @gconstable,

I have the same issue, can you explain what went wrong with mangento 2.3 ?

when I save configuration return a 404 magento page.

thanks,
Dave

**Comment by gconstable** [comment]
Hi Dave,
  If i remember correctly, i had a few issues in my setup:

One issue i had was permissions, i believe that pimgento installed fine but for some reason my web server did not display correctly until i changed all the file permissions to 777 (for testing) on linux.

I also believe that i had a php issue as well which was not helping.  I believe it was a missing module.

Sorry i am not very detailed, i should of made more notes but i had so many issues and a deadline that i was rushing allot.

I hope this helps.

**Comment by daveaie** [comment]
Resolved, my problem is on akeneo host accessibility.

thanks,
best regards
