### ISSUE TITLE
Provide override api documentation

### ISSUE THREAD

**Issue by chandrantwins** [Agence-DnD/PIMGento-2-API#59]
Hi PIMGento Team,

Really appreciate your work . Please update documentation to explain how to override API. That will be more helpful for beginners.

Thanks
Chandran Nepolean

**Comment by Dnd-Gimix** [comment]
Hi @chandrantwins ,

Thank you for using PIMGento2 API !

What kind of documentation are you looking for: 
- A documentation to override PIMGento2 API module ?
- Or a documentation to override Akeneo API ?

Thank you.
Regards,

**Comment by Dnd-Gimix** [comment]
@chandrantwins ,

Did you read the documentation ?

Regards,

**Comment by chandrantwins** [comment]
Hi Team

I am planning to override pimgento API. because there is  custom change needed. i have checked documentation.. there is no example for how to override.. if anything please give me specific link

Thanks
Chandran

**Comment by Dnd-Gimix** [comment]
Hi @chandrantwins ,

PIMGento 2 API is a regular extension that doesn't have any specificity regarding the rewrite process of Magento 2.

If you are aware of the rewrite syntax of Magento 2, you should be able to rewrite the connector easily.

Plus, many tutorials are available on the web to show you how to do so : 

- https://inchoo.net/magento-2/overriding-classes-magento-2/
- https://magenticians.com/override-model-magento-2/
- https://webkul.com/blog/overriding-rewriting-classes-magento2/
- https://www.mageplaza.com/devdocs/how-use-plugin-preference-rewrite-block-model-controller-helper-magento-2.html

Hope it helps !

Regards,

**Comment by Dnd-Gimix** [comment]
Hi @chandrantwins ,

As your question has been answered and is not concerning directly PIMGento 2 API, I'll close this issue.

Do not hesitate to open a new one if needed.

Have a good day !

Regards,
