### ISSUE TITLE
attribute_code en majuscule

### ISSUE THREAD

**Issue by alex5513** [Agence-DnD/PIMGento-2-API#82]
Bonjour,

j'ai cette erreur quand je modifie des attributs "Code attribut "PRODUCT_LINE_GROUP" invalide. Veuillez utiliser uniquement des lettres (a-z), des chiffres (0-9) ou underscore (_), le premier caractère doit être une lettre."

Est-ce qu'il y'a une option pour importer les attributs en minuscule même si ils sont en majuscules dans akeneo ? Vu que Magento supporte pas les attributs en maj.

Cordialement

Alex

**Comment by Dnd-Gimix** [comment]
Bonjour Alex,

Merci d'utiliser PIMGento 2 API.

Nous sommes au courant de ce problème et @dnd-derwent a déjà ouvert une PR à ce sujet : https://github.com/Agence-DnD/PIMGento-2-API/pull/79

Les modifications seront déployées lors de la prochaine release du module.

Cordialement,

**Comment by alex5513** [comment]
Ok super !

Vous avez une petite idée de quand sortira la prochaine release ?

Cordialement 

Alex

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513,

La prochaine release est prévue demain, je reviendrai vers vous pour vous confirmer sa mise en ligne.

Bonne journée.

Cordialement,

**Comment by alex5513** [comment]
Ca marche 

Merci bonne journée à vous

Cordialement

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513 ,

Le nouvelle release 100.2.2 comprenant le correctif pour les noms d'attributs en majuscule est sortie : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.2

Pourriez-vous revenir vers nous une fois le correctif testé de votre côté ?
Merci d'avance.

Cordialement,

**Comment by alex5513** [comment]
C'est fonctionnel merci pour l'update  !

Cordialement

Alex

**Comment by Dnd-Gimix** [comment]
Merci pour votre confirmation, je ferme cette issue.

Cordialement,
