### ISSUE TITLE
Notice: Undefined offset when importing Products

### ISSUE THREAD

**Issue by randomresult** [Agence-DnD/PIMGento-2-API#87]
Hi There, 

iam running Magento 2.3 on php7.2 with the latest release of PimgentoAPI.
I can run all Imports in the provided sorting. When i come to products i get the following error: 

    product
    [08:11:08] Start import
    [08:11:08] Import ID : 5c76461c354fa
    [08:11:08] Create temporary table
    [08:11:09] completed
    [08:11:09] Fill temporary table
    [08:11:11] 23 line(s) found
    [08:11:11] Add required data
    [08:11:12] completed
    [08:11:12] Create configurables
    [08:11:14] completed
    [08:11:14] Match code with Magento ID
    [08:11:15] completed
    [08:11:15] Match family code with Magento ID
    [08:11:16] completed
    [08:11:16] Update column values for options
    [08:11:17] completed
    [08:11:17] Create or update product entities
    [08:11:19] completed
    [08:11:19] Set values to attributes
    [08:11:20] Notice: Undefined offset: 1 in /html/develop/releases/20190226151745/vendor/agencednd/module-pimgento-2-api/Job/Product.php on line 891

I am having only standard akeneo attributes but use Mulitselects in there. 
Right now i want to import 3 Product.Models with 26 Singleproducts. These get imported but without any Attributes. (as far as i can see).
What to do? Am i missing something?

**Comment by Dnd-Gimix** [comment]
Hello @randomresult ,

Thank you for using PIMGento 2 API.
We have aknowledged the issue and provided a fix for it in : https://github.com/Agence-DnD/PIMGento-2-API/pull/88

This fix will be added to next week release, but in the meantime you can manually apply this fix to your installation.
Can you confirm that it works now ?

For your configurable product, you have to fill the configurable product mapping with the attributes you want to retreive from product models.

Regards,

**Comment by randomresult** [comment]
i now have the following in my Composer.json
`"agencednd/module-pimgento-2-api": "dev-hotfix/product_scope",` and the import now works. 

Any idea when the next release is about to come?

**Comment by Dnd-Gimix** [comment]
Hi @randomresult ,

Glad it fixed your issue.

We usually release a new version of the connector every two weeks, so the next release should be online by the end of next week.

Have a good day !

Regards,

**Comment by rakibabu** [comment]
@Dnd-Gimix 

Can you release it earlier? I've the same issue.

**Comment by Dnd-Gimix** [comment]
Hello @rakibabu ,

Unfortunately we won't be able to draft a new release before next week.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @randomresult @rakibabu ,

New release 100.2.3 is out with the fix for this issue, can you update your connector ?
Thank you very much.

Regards,

**Comment by randomresult** [comment]
I did. still having issues but i think they are configuration-related. I dont get the products displayed in the frontend. Any support email or something. searching like crazy. Paid-Support?

**Comment by Dnd-Gimix** [comment]
Hello @randomresult ,

As this connector is maintained and developed for free, we are unfortunately not offering paid support on it.

Did you checked your Magento and your product configuration : 
- Stock
- Price
- Visibility
- Display rules in the catalog configuration
- Category / website assignation
- Indexes / Caches

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @randomresult ,

Did you managed to display your products ?
Can we close this issue ?

Regards,

**Comment by Dnd-Gimix** [comment]
Hello,

Without answer, I'll close this issue.
Please feel free to open a new one if necessary.

Regards,
