### ISSUE TITLE
Produits configurable sans infos

### ISSUE THREAD

**Issue by alex5513** [Agence-DnD/PIMGento-2-API#90]
Bonjour,

Lorsque j'ai réalisé tous les imports, tous les produits simples sont correctement créés.
Par contre les produits configurables sont sans infos, sans noms etc, il y'a juste le sku et les produits simples associés au produit avec le bon attribut variant d'Akénéo.

Dans Akénéo le product variant a les infos.

Je ne sais pas si y'a une configuration à modifier.

Avez vous déjà rencontré ce problème ?

Cordialement

Alex

**Comment by Dnd-Gimix** [comment]
Hello @alex5513 ,

Pourriez-vous renseigner dans la configuration du mapping des produits configurables l'ensemble des attributs que vous souhaitez récupérer des produits model ?
Le champ "value" peut rester vide dans votre cas.

Merci.

Cordialement,

**Comment by alex5513** [comment]
C'est fait, effectivement ca fonctionne ! Merci beaucoup

**Comment by Dnd-Gimix** [comment]
Merci @alex5513 pour votre retour !

Bonne soirée.

Cordialement,
