### ISSUE TITLE
Import of many products

### ISSUE THREAD

**Issue by matthiashamacher** [Agence-DnD/PIMGento-2-API#95]
Hello there,
We currently want to run an import with round about 3000 Products with Images and URL rewrite regeneration, but the import doesn't finish. There where no errors and in the PIMGento-Logs the import status is processing. With some other products, we fixed this by importing one family after the other. But this is one family so we cannot split the import, by using the filter.
Any ideas what we can do?

**Comment by stefanfr** [comment]
@matthiashamacher Try increasing `max_allowed_packet` within your mysql config

**Comment by Dnd-Gimix** [comment]
Hello @matthiashamacher ,

You might also want to increase the PHP timeout value.
Are you launching the import on the admin interface ?

If yes, you can open your browser console and follow the ajax request progress to see if any error is prompted.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @matthiashamacher ,

Any news or feedback on this subject ?
We have released a new version yesterday containing performance and data quantity improvement, you might be interested by upgrading your connector : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.5

Regards,

**Comment by Dnd-Gimix** [comment]
Hello,

Without answer on this subject, I'll close the issue.
Please, feel free to open a new one if the problem persists.

Regards,
