### ISSUE TITLE
Row size too large

### ISSUE THREAD

**Issue by alex5513** [Agence-DnD/PIMGento-2-API#96]
Bonjour,

Sur mon environnement de test, lors de l'import Product Model, j'ai cette erreur : 

![Capture d’écran 2019-03-11 à 15 05 03](https://user-images.githubusercontent.com/6359584/54129740-37a0e400-440f-11e9-88af-ab228fe15000.png)

Cordialement

Alex

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513 ,

Merci d'utiliser le connecteur PIMGento 2 API.

Nous venons de sortir une nouvelle version du connecteur qui contient quelques améliorations en terme de performance et surtout de quantité de données transférées durant les imports : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.5

Pourriez-vous mettre à jour votre connecteur et tester de nouveau pour vérifier si l'erreur est toujours présente ?

Merci d'avance.

Cordialement,

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513 ,

Est-ce que vous rencontrez toujours le problème ?

Cordialement,
Rémi.

**Comment by alex5513** [comment]
Bonjour Rémi,

Je n'ai plus le problème, vous pouvez fermer le ticket.

Merci

Cordialement
Alexis

**Comment by Dnd-Gimix** [comment]
Bonjour @alex5513 ,

Merci, nous fermons cette issue.

Cordialement,
